---
ID: "47ed53e6-b8a4-4008-a322-81c4ae6d487a"
Parent: "a6cb9b31-57da-484f-93ce-2613d5cd2156"
Template: "a6cb9b31-57da-484f-93ce-2613d5cd2156"
Path: /sitecore/templates/Foundation/Zodiac/Labels/Label Group/__Standard Values
DB: master
SharedFields:
- ID: "4c9312a5-2e4e-42f8-ab6f-b8db8b82bf22"
  Hint: __Controller
  Value: Foundation.Labels.LabelController,Foundation.Labels
- ID: "9fb734cc-8952-4072-a2d4-40f890e16f56"
  Hint: __Controller Action
  Value: Index
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181113T150603Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rcabral
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rcabral
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b05f050a-eebe-452e-bbf4-f5aa9adad4fc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200812T144024Z
